### ISSUE TITLE
Dock plugins were not detected

### ISSUE THREAD

**Issue by annanya-tamu** [open-navigation/opennav_docking#62]
**Required Info:**

- Operating System: Ubuntu 22.04 LTS
- ROS2 Version: ROS2 Humble
- DDS implementation: rmw_fastrtps_cpp. Tried with Cyclone DDS as well

Hi,

I just added the docking nodes as a composable node in my launch file as such:
```
lifecycle_nodes = ['controller_server',
                       'smoother_server',
                       'planner_server',
                       'behavior_server',
                       'bt_navigator',
                       'waypoint_follower',
                       'velocity_smoother',
                       'docking_server']
```
```
Node(
                package='opennav_docking',
                executable='opennav_docking',
                name='docking_server',
                output='screen',
                respawn=use_respawn,
                respawn_delay=2.0,
                parameters=[configured_params],
                arguments=['--ros-args', '--log-level', log_level],
                remappings=remappings,
            ),
```
```
ComposableNode(
                        package='opennav_docking',
                        plugin='opennav_docking::DockingServer',
                        name='docking_server',
                        parameters=[configured_params],
                        remappings=remappings,
                    ),
```
I have the default plugins specified in my nav2_params.yaml file as such:

```
docking_server:
  ros__parameters:
    controller_frequency: 50.0
    initial_perception_timeout: 5.0
    wait_charge_timeout: 5.0
    dock_approach_timeout: 30.0
    undock_linear_tolerance: 0.05
    undock_angular_tolerance: 0.1
    max_retries: 3
    base_frame: "base_link"
    fixed_frame: "odom"
    dock_backwards: false
    dock_prestaging_tolerance: 0.5

    # Types of docks
    dock_plugins: ['simple_charging_dock']
    simple_charging_dock:
      plugin: 'opennav_docking::SimpleChargingDock'
      docking_threshold: 0.05
      staging_x_offset: -0.7
      use_external_detection_pose: true
      use_battery_status: false # true
      use_stall_detection: false # true

      external_detection_timeout: 1.0
      external_detection_translation_x: -0.18
      external_detection_translation_y: 0.0
      external_detection_rotation_roll: -1.57
      external_detection_rotation_pitch: -1.57
      external_detection_rotation_yaw: 0.0
      filter_coef: 0.1

    # Dock instances
    # The following example illustrates configuring dock instances.
    docks: ['home_dock']  # Input your docks here
    home_dock:
      type: 'simple_charging_dock'
      frame: map
      pose: [0.0, 0.0, 0.0]

    controller:
      k_phi: 3.0
      k_delta: 2.0
      v_linear_min: 0.15
      v_linear_max: 0.15
```

However when I launch navigation_launch,py, I get the following error: 
`[opennav_docking-8] [ERROR] [1728923077.655240967] [docking_server]: Charging dock plugins not given!
[lifecycle_manager-9] [ERROR] [1728923077.655614486] [lifecycle_manager_navigation]: Failed to change state for node: docking_server
[lifecycle_manager-9] [ERROR] [1728923077.655628225] [lifecycle_manager_navigation]: Failed to bring up all requested nodes. Aborting bringup.`

I'm not sure what's going on since the plugins were specified in the nav2_params.yaml file. Any help on this would be much appreciated!
