### ISSUE TITLE
Unable to connect "use_external_detection_pose" April tag

### ISSUE THREAD

**Issue by PrathameshCOLLABINT** [open-navigation/opennav_docking#83]
Hi Team,

i am using this library for auto_docking for my simulated robot.

robot is does able to dock at pose i have gievn from nav config file.

currently i am facing issue to dock in "april tag" pose. 

am attaching all the information i can attached kindly guide me why robot is not able to dock at april tag pose.

Nav2_params.yamal file 

```
docking_server:
  ros__parameters:
    controller_frequency: 50.0
    initial_perception_timeout: 20.0 #5.0
    wait_charge_timeout: 5.0
    dock_approach_timeout: 30.0
    undock_linear_tolerance: 0.05
    undock_angular_tolerance: 0.1
    max_retries: 3
    base_frame: "base_link"
    fixed_frame: "odom"
    odom_topic: "odom"
    dock_backwards: false  # Deprecated, use dock_direction in plugin
    dock_prestaging_tolerance: 0.5
    service_introspection_mode: "disabled"

    # Types of docks
    dock_plugins: ['dock0']
    dock0:
      plugin: 'opennav_docking::SimpleChargingDock'  # Also 'opennav_docking::SimpleNonChargingDock'
      docking_threshold: 0.05
      staging_x_offset: -0.7
      use_external_detection_pose: true
      use_battery_status: true # true
      use_stall_detection: false
      rotate_to_dock: false

      external_detection_timeout: 1.0
      external_detection_translation_x: -0.18
      external_detection_translation_y: 0.0
      external_detection_rotation_roll: -1.57
      external_detection_rotation_pitch: -1.57
      external_detection_rotation_yaw: 0.0
      filter_coef: 0.1
      dock_direction: "forward" # "backward"

    # Dock instances
    docks: ['home_dock']
    home_dock:
      type: 'dock0'
      frame: map
      pose: [2.0, 2.0, 0.0]
      id: '0'

    # Dock instances
    # dock_database: $(find-pkg-share my_robot_apriltag)/config/dock_database.yaml
    
    controller:
      k_phi: 3.0
      k_delta: 2.0
      v_linear_min: 0.15
      v_linear_max: 0.15
      v_angular_max: 0.75
      slowdown_radius: 0.25
      rotate_to_heading_angular_vel: 1.0
      rotate_to_heading_max_angular_accel: 3.2
      use_collision_detection: true
      costmap_topic: "local_costmap/costmap_raw"
      footprint_topic: "local_costmap/published_footprint"
      transform_tolerance: 0.1
      projection_time: 5.0
      simulation_time_step: 0.1
      dock_collision_threshold: 0.3
```

Subscribing and publishing the /detected_doc_pose properly

![Image](https://github.com/user-attachments/assets/67ffb01d-c2b4-437e-a1cc-820a1933c7e4)

ros2 topic echo  /detected_dock_pose data as follows

```
header:
  stamp:
    sec: 1747927731
    nanosec: 955586641
  frame_id: camera_depth_optical_frame
pose:
  position:
    x: -0.06161046130607417
    y: -0.09561987834144685
    z: 0.7694382576018706
  orientation:
    x: 0.9505029731461062
    y: -0.0037829757385641318
    z: 0.3104250191130356
    w: -0.012887771089117143
---

```
but /doc_pose is not giving any value when i did echo.
![Image](https://github.com/user-attachments/assets/d103911d-cbd4-415d-901f-453bd1bc183f)

tf tree is like

![Image](https://github.com/user-attachments/assets/405a02b3-a290-4222-9823-ca8a126d4b62)

calling on nav2_launch file is like

```
    lifecycle_nodes = ['controller_server',
                       'smoother_server',
                       'planner_server',
                       'behavior_server',
                       'bt_navigator',
                       'waypoint_follower',
                       'velocity_smoother',
                       'docking_server']


            Node(
                package='nav2_lifecycle_manager',
                executable='lifecycle_manager',
                name='lifecycle_manager_navigation',
                output='screen',
                arguments=['--ros-args', '--log-level', log_level],
                parameters=[{'use_sim_time': use_sim_time},
                            {'autostart': autostart},
                            {'node_names': lifecycle_nodes}]),
            Node(
                package='opennav_docking',
                executable='opennav_docking',
                name='docking_server',
                output='screen',
                respawn=use_respawn,
                respawn_delay=2.0,
                parameters=[configured_params],
                arguments=['--ros-args', '--log-level', log_level],
                remappings=remappings,
            ),

            ComposableNode(
                package='nav2_lifecycle_manager',
                plugin='nav2_lifecycle_manager::LifecycleManager',
                name='lifecycle_manager_navigation',
                parameters=[{'use_sim_time': use_sim_time,
                             'autostart': autostart,
                             'node_names': lifecycle_nodes}]),
            ComposableNode(
                package='opennav_docking',
                plugin='opennav_docking::DockingServer',
                name='docking_server',
                parameters=[configured_params],
                remappings=remappings,
                    ),
```
and in simulation it is like this

![Image](https://github.com/user-attachments/assets/d47e0d68-1f1e-40e8-a85b-059ffa91dab6)
